import "../css/owfont-regular.css";
import "../css/style.css";
import { showTime } from "./time.js";
import setLocalStorage from "./name.js";
import getBg from "./bg.js";
import getWeather from "./weather.js";
import loadQuote from "./quotes.js";
import player from "./player.js";
import Todo from "./Todo/Todo.js";
import Settings from "./Static/static.js";
import setSettingsList from "./settingsList.js";

setSettingsList();
showTime();
setLocalStorage();
getBg();
getWeather();
loadQuote();
player();
Todo();
new Settings("div", "settings", document.body);
